title: RookieOven
description: Creating a more vibrant startup community in Scotland with our gorgeous coworking space, regular events and education programmes.
email: michael@rookieoven.com
url: "https://rookieoven.com"
image: "/images/academy-top.jpg"
twitter_username: rookieoven
gems: [bourbon, neat, jekyll-sitemap, jekyll-minifier, jekyll-paginate]
paginate: 10
paginate_path: "/blog/page:num"
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "blog-post"
exclude:
  - divshot.json
