title: RookieOven
description: Baking a tasty startup scene in Scotland. Creating a more cohesive startup community in Scotland through a coworking space and regular meetups
email: michael@rookieoven.com
url: "http://rookieoven.com"
twitter_username: rookieoven
gems: [bourbon, neat, jekyll-sitemap, jekyll-minifier, jekyll-paginate]
paginate: 10
paginate_path: "/blog/page:num"
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "blog-post"
exclude:
  - divshot.json
